### PR TITLE
bugfix: run generate for fix statik

### PR DESCRIPTION
**Pull request by woorui**
fix for ignoring statik generate

### CODE REVIEW

**Comment by Windfarer** [comment]
Could you describe the detail of this fixing?

**Comment by woorui** [comment]
> Could you describe the detail of this fixing?

I found the select-box to select service was not show, I remove statik `-m` flag and re-run `go generate`, It's work.

**Comment by Windfarer** [comment]
[https://github.com/rakyll/statik#deterministic-output](https://github.com/rakyll/statik#deterministic-output) argument `-m` is for ignoring the last modified time, if remove it, may cause static files can not be updated when the embed files being updated. Could you dive into the browser's devtool, check the console output and the index.html content to see the actual reason of this issue?

**Comment by woorui** [comment]
I run `example/helloworld`, index.html don't have select logic on main branch.

**Comment by Windfarer** [comment]
I've tried with many different browsers and the latest main branch code, but can not reproduce your problem.

**Comment by woorui** [comment]
I think it related to browser `last-modified` header.
After I update new version, Because your ignores the `mtime` by `-m` flag, my browser thinks that the file has not changed, 304 and return old file.
Then I ran it, I found that the behavior was different from the doc.
So I remove `-m `flag and re-generate, `last-modified` changed, my browser don't do 304, and ask server for new file.
I thought it is a bug that moment. I'am sorry to this pr, It's my problem.

**Pull request closed without merging**
